#!/usr/bin/env python3
"""Bundle the visualizer into a single self-contained standalone.html.

Inlines app.js and every vendor/*.js referenced by index.html so the result
runs from a double-click with no server, network, or sibling files.
"""
import re
from pathlib import Path

ROOT = Path(__file__).parent


def inline(match: re.Match) -> str:
    src = match.group(1)
    code = (ROOT / src).read_text(encoding="utf-8")
    # a literal close tag inside inlined JS would end the script block early
    code = code.replace("</script>", "<\\/script>")
    return "<script>/* inlined: " + src + " */\n" + code + "\n</script>"


def main() -> None:
    html = (ROOT / "index.html").read_text(encoding="utf-8")
    html, n = re.subn(r'<script src="([^"]+)"></script>', inline, html)
    if n != 5:
        raise SystemExit(f"expected 5 script tags to inline, found {n}")
    html = html.replace(
        "<!DOCTYPE html>\n",
        "<!DOCTYPE html>\n<!-- GENERATED by build_standalone.py — "
        "single-file bundle of index.html + app.js + vendor/. "
        "Edit those sources, then rerun the script. -->\n",
        1,
    )
    out = ROOT / "standalone.html"
    out.write_text(html, encoding="utf-8")
    print(f"wrote {out} ({out.stat().st_size / 1024:.0f} KB, {n} scripts inlined)")


if __name__ == "__main__":
    main()
